name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Model Inference
      id: model-inference
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Model Inference
        setup-command: pip3 install pytest pandas argparse
        command: pytest model_test.py::test_inference
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MODEL-INFERENCE_RESULTS: "${{steps.model-inference.outputs.result}}"
      with:
        runners: model-inference
