name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Model Inference
      id: model-inference
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Model Inference
        setup-command: pip3 install pytest pandas argparse
        command: pytest model_test.py::test_inference
        timeout: 10
        max-score: 50
    - name: relu()
      id: relu
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: relu()
        setup-command: ''
        command: pytest model_test.py::test_relu
        timeout: 10
        max-score: 10
    - name: softmax()
      id: softmax
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: softmax()
        setup-command: ''
        command: model_test.py::test_softmax
        timeout: 10
        max-score: 10
    - name: Accuracy >= 80
      id: accuracy-80
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Accuracy >= 80
        setup-command: ''
        command: pytest model_test.py::test_acc_80
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MODEL-INFERENCE_RESULTS: "${{steps.model-inference.outputs.result}}"
        RELU_RESULTS: "${{steps.relu.outputs.result}}"
        SOFTMAX_RESULTS: "${{steps.softmax.outputs.result}}"
        ACCURACY-80_RESULTS: "${{steps.accuracy-80.outputs.result}}"
      with:
        runners: model-inference,relu,softmax,accuracy-80
